{
  # lsp.servers.ltex_plus.config.settings.ltex.dictionary = {
  dictionary = {
    en-US = [
      "ags"
      "fzf"
      "Gitsigns"
      "Vimtex"
      "dap"
      "neotest"
    ];
  };

  # lsp.servers.ltex_plus.config.filetypes = [
  filetypes = [
    # Default values (https://github.com/neovim/nvim-lspconfig/blob/master/doc/configs.md#ltex_plus)
    "asciidoc"
    "bib"
    "context"
    "gitcommit"
    "html"
    "markdown"
    "org"
    "pandoc"
    "plaintex"
    "quarto"
    "mail"
    "mdx"
    "rmd"
    "rnoweb"
    "rst"
    "tex"
    "text"
    "typst"
    "xhtml"

    # Code languages
    "c"
    "cpp"
    "clojure"
    "dart"
    "elixir"
    "elm"
    "erlang"
    "fsharp"
    "go"
    "groovy"
    "haskell"
    "java"
    "javascript"
    "javascriptreact"
    "julia"
    "kotlin"
    "lisp"
    "lua"
    "matlab"
    "perl"
    "perl6"
    "php"
    "puppet"
    "python"
    "r"
    "ruby"
    "rust"
    "scala"
    "sql"
    "swift"
    "typescript"
    "typescriptreact"
    "verilog"
    "vb"
  ];

  # lsp.servers.ltex_plus.config.settings.ltex.enabled = [
  enabled = [
    # Default markup languages (https://ltex-plus.github.io/ltex-plus/supported-languages.html#markup-languages)
    "asciidoc"
    "bib"
    "context"
    "gitcommit"
    "html"
    "markdown"
    "org"
    "pandoc"
    "plaintex"
    "quarto"
    "mail"
    "mdx"
    "rmd"
    "rnoweb"
    "rst"
    "tex"
    "latex"
    "text"
    "typst"
    "xhtml"

    # Supported coding languages (https://ltex-plus.github.io/ltex-plus/supported-languages.html#programming-languages)
    "c"
    "cpp"
    "clojure"
    "dart"
    "elixier"
    "elm"
    "erlang"
    "fsharp"
    "go"
    "groovy"
    "haskell"
    "java"
    "javascript"
    "javascriptreact"
    "julia"
    "kotlin"
    "lisp"
    "lua"
    "matlab"
    "perl"
    "perl6"
    "php"
    "puppet"
    "python"
    "r"
    "ruby"
    "rust"
    "scala"
    "sql"
    "swift"
    "typescript"
    "typescriptreact"
    "verilog"
    "vb"
  ];
}
