keys:
  - &desktop age1rx2kpktacmwt88l2yx65guvzkzp56y6ky5va0rce6nflx0fnkf4skusylu
  - &thinkpad age15xtfp9s5rupc80na9nd2jmaevtk4cckzpgj439t9tul4c889u49qc06fhh
  - &demenik_desktop age13rafcj20798yffxd9cy89v8t0lc5xxf7d3lky5pfr73gzgfrxvusdyjmfk
  - &demenik_thinkpad age1a5t2a68zzpy9snecxh2f3ph0s9ruky4e6ywvfmjdeujy36kugptqdw4x3h
creation_rules:
  - path_regex: hosts/.*\.sops\.yaml$
    key_groups:
      - age:
          - *desktop
          - *thinkpad
          - *demenik_desktop
          - *demenik_thinkpad
  - path_regex: users/.*\.sops\.yaml$
    key_groups:
      - age:
          - *demenik_desktop
          - *demenik_thinkpad
