{
  name = "librewolf";

  modules = [../default.nix];
  moduleConfig = {
    pkgs,
    lib,
    ...
  }: {
    browser = {
      command = lib.getExe pkgs.librewolf;
      windowClass = "librewolf";
      desktopFileName = "librewolf.desktop";
    };

    wm.windowrules = [
      {
        matchClass = "librewolf";
        matchTitle = "Picture-in-Picture";

        floating = true;
        keepAspectRatio = true;
        pinned = true;
        position = ["100%-w-5" "100%-h-5"];
      }
    ];
  };

  home = {
    pkgs,
    lib,
    config,
    ...
  }: {
    imports = [
      ./search.nix
    ];

    home.packages = with pkgs; [
      nerd-fonts.symbols-only
    ];

    programs.librewolf = {
      enable = true;
      package = pkgs.librewolf;

      profiles.default = {
        name = "Default";

        settings = {
          "extensions.pocket.enabled" = false;

          "browser.urlbar.suggest.engines" = false;
          "browser.urlbar.suggest.openpage" = false;
          "browser.urlbar.suggest.bookmark" = true;
          "browser.toolbars.bookmarks.visibility" = "never";
          "browser.urlbar.suggest.addons" = false;
          "browser.urlbar.suggest.pocket" = false;

          "widget.use-xdg-desktop-portal.file-picker" = 1;

          "browser.formfill.enable" = false;
          "extensions.formautofill.addresses.enabled" = false;
          "security.warn_submit_secure_to_insecure" = false;

          "font.name.monospace.x-western" = builtins.head config.fonts.fontconfig.defaultFonts.monospace;
          "font.name.sans-serif.x-western" = builtins.head config.fonts.fontconfig.defaultFonts.sansSerif;
          "font.name.serif.x-western" = builtins.head config.fonts.fontconfig.defaultFonts.serif;
        };

        userChrome = import ./userChrome;

        userContent = let
          inherit (config.fonts.fontconfig.defaultFonts) monospace emoji;
        in ''
          code, kbd, pre, samp, tt {
            font-family: "${builtins.head monospace}", "${builtins.head emoji}", "Symbols Nerd Font", monospace !important;
            font-variant-ligatures: none;
          }
        '';
      };
    };

    theme.templates.pywalfox = {
      enable = true;
      target = "~/.cache/wal/colors.json";
      text =
        # json
        ''
          {
            "wallpaper": "{{image}}",
            "alpha": "100",
            "colors": {
              "color0": "{{colors.surface.dark.hex}}",
              "color1": "",
              "color2": "",
              "color3": "{{colors.primary.default.hex}}",
              "color4": "",
              "color5": "{{colors.tertiary.default.hex}}",
              "color6": "",
              "color7": "{{colors.surface_container_highest.default.hex}}",
              "color8": "",
              "color9": "",
              "color10": "{{colors.primary.default.hex}}",
              "color11": "",
              "color12": "",
              "color13": "{{colors.secondary.default.hex}}",
              "color14": "",
              "color15": "{{colors.on_background.default.hex}}"
            }
          }
        '';
      post_hook = "${lib.getExe pkgs.pywalfox-native} update";
    };
    home.file.".librewolf/native-messaging-hosts/pywalfox.json".text = builtins.toJSON {
      name = "pywalfox";
      description = "Automatically theme your browser using the colors generated by Pywal";
      path = lib.getExe pkgs.pywalfox-native;
      type = "stdio";
      allowed_extensions = ["pywalfox@frewacom.org"];
    };
  };
}
