version = 3
final_space = true

[transient_prompt]
template = ' '
foreground = '#f9e2af'
background = 'transparent'

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
template = '{{ .UserName }}@{{ .HostName }} '
foreground = '#cba6f7'
type = 'session'
style = 'plain'

[blocks.segments.properties]
cache_duration = 'none'

[[blocks.segments]]
template = '{{ if ne .Type "unknown" }}󱄅 {{ end }}'
foreground = '#89b4fa'
type = 'nix-shell'
style = 'plain'

[blocks.segments.properties]
cache_duration = 'none'

[[blocks.segments]]
template = 'in'
foreground = '#585b70'
type = 'text'
style = 'plain'

[blocks.segments.properties]
cache_duration = 'none'

[[blocks.segments]]
foreground = '#89dceb'
type = 'path'
style = 'powerline'

[blocks.segments.properties]
cache_duration = 'none'
style = 'full'

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
template = ''
foreground = '#f9e2af'
type = 'text'
style = 'plain'

[blocks.segments.properties]
cache_duration = 'none'
